Easy test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -6,97 +6,97 @@ on:
     branches: [ main ]
   workflow_dispatch:
 jobs:
-  build-test:
-    runs-on: ubuntu-latest
-    steps:
+  #build-test:
+  #  runs-on: ubuntu-latest
+  #  steps:
 
     # Prepare
-      - uses: actions/checkout@v2
-      - name: Set up JDK 17
-        uses: actions/setup-java@v2
-        with:
-          java-version: '17'
-          distribution: 'adopt'
+  #    - uses: actions/checkout@v2
+  #    - name: Set up JDK 17
+  #      uses: actions/setup-java@v2
+  #      with:
+  #        java-version: '17'
+  #        distribution: 'adopt'
         
-      - name: Validate Gradle wrapper
-        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
+  #    - name: Validate Gradle wrapper
+  #      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
+  #    - name: Set up Docker Buildx
+  #      uses: docker/setup-buildx-action@v3
       
-      - name: Install Docker
-        run: |
-          curl -fsSL https://get.docker.com -o get-docker.sh
-          sudo sh get-docker.sh
-          sudo usermod -aG docker $USER
+  #    - name: Install Docker
+  #      run: |
+  #        curl -fsSL https://get.docker.com -o get-docker.sh
+  #        sudo sh get-docker.sh
+  #        sudo usermod -aG docker $USER
         
-      - name: Install Docker Compose
-        run: |
-          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
-          sudo chmod +x /usr/local/bin/docker-compose
-          docker-compose --version
+  #    - name: Install Docker Compose
+  #      run: |
+  #        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+  #        sudo chmod +x /usr/local/bin/docker-compose
+  #        docker-compose --version
 
       #- name: Set up Docker Buildx
       #  uses: docker/setup-buildx-action@v3
         
-      - name: Set up Kafka Docker Compose 
-        run: docker-compose -f docker-compose.yml up -d
+  #    - name: Set up Kafka Docker Compose 
+  #      run: docker-compose -f docker-compose.yml up -d
       
       # Build
-      - name: Sanitize kafka I
-        run: ./gradlew build --no-daemon || true
-        env:
-          NINJA_PROFANITY_FILTER_API_KEY: ${{ secrets.NINJA_PROFANITY_FILTER_API_KEY }}
-          GOOGLE_SAFE_BROWSING_API_KEY: ${{ secrets.GOOGLE_API_SAFETY_KEY }}
+  #    - name: Sanitize kafka I
+  #      run: ./gradlew build --no-daemon || true
+  #      env:
+  #        NINJA_PROFANITY_FILTER_API_KEY: ${{ secrets.NINJA_PROFANITY_FILTER_API_KEY }}
+  #        GOOGLE_SAFE_BROWSING_API_KEY: ${{ secrets.GOOGLE_API_SAFETY_KEY }}
 
-      - name: Sanitize kafka II
-        run: ./gradlew build --no-daemon || true
-        env:
-          NINJA_PROFANITY_FILTER_API_KEY: ${{ secrets.NINJA_PROFANITY_FILTER_API_KEY }}
-          GOOGLE_SAFE_BROWSING_API_KEY: ${{ secrets.GOOGLE_API_SAFETY_KEY }}
-          KAFKA_BROKER_IP: localhost:9092
+  #    - name: Sanitize kafka II
+  #      run: ./gradlew build --no-daemon || true
+  #      env:
+  #        NINJA_PROFANITY_FILTER_API_KEY: ${{ secrets.NINJA_PROFANITY_FILTER_API_KEY }}
+  #        GOOGLE_SAFE_BROWSING_API_KEY: ${{ secrets.GOOGLE_API_SAFETY_KEY }}
+  #        KAFKA_BROKER_IP: localhost:9092
 
-      - name: Build with Gradle
-        run: ./gradlew build --no-daemon
-        env:
-          GOOGLE_SAFE_BROWSING_API_KEY: ${{ secrets.GOOGLE_API_SAFETY_KEY }}
-          GOOGLE_CLIENT_ID_API_KEY: ${{ secrets.GOOGLE_CLIENT_ID_API_KEY }}
-          GOOGLE_CLIENT_SECRET_API_KEY: ${{ secrets.GOOGLE_CLIENT_SECRET_API_KEY }}
-          NINJA_PROFANITY_FILTER_API_KEY: ${{ secrets.NINJA_PROFANITY_FILTER_API_KEY }}
-          KAFKA_BROKER_IP: localhost:9092
+  #    - name: Build with Gradle
+  #      run: ./gradlew build --no-daemon
+  #      env:
+  #        GOOGLE_SAFE_BROWSING_API_KEY: ${{ secrets.GOOGLE_API_SAFETY_KEY }}
+  #        GOOGLE_CLIENT_ID_API_KEY: ${{ secrets.GOOGLE_CLIENT_ID_API_KEY }}
+  #        GOOGLE_CLIENT_SECRET_API_KEY: ${{ secrets.GOOGLE_CLIENT_SECRET_API_KEY }}
+  #        NINJA_PROFANITY_FILTER_API_KEY: ${{ secrets.NINJA_PROFANITY_FILTER_API_KEY }}
+  #        KAFKA_BROKER_IP: localhost:9092
       
-      # Test
-      - name: Test with Gradle
-        run: ./gradlew check --no-daemon
-        env:
-          GOOGLE_SAFE_BROWSING_API_KEY: ${{ secrets.GOOGLE_API_SAFETY_KEY }}
-          GOOGLE_CLIENT_ID_API_KEY: ${{ secrets.GOOGLE_CLIENT_ID_API_KEY }}
-          GOOGLE_CLIENT_SECRET_API_KEY: ${{ secrets.GOOGLE_CLIENT_SECRET_API_KEY }}
-          NINJA_PROFANITY_FILTER_API_KEY: ${{ secrets.NINJA_PROFANITY_FILTER_API_KEY }}
-          KAFKA_BROKER_IP: localhost:9092
+  #    # Test
+  #    - name: Test with Gradle
+  #      run: ./gradlew check --no-daemon
+  #      env:
+  #        GOOGLE_SAFE_BROWSING_API_KEY: ${{ secrets.GOOGLE_API_SAFETY_KEY }}
+  #        GOOGLE_CLIENT_ID_API_KEY: ${{ secrets.GOOGLE_CLIENT_ID_API_KEY }}
+  #        GOOGLE_CLIENT_SECRET_API_KEY: ${{ secrets.GOOGLE_CLIENT_SECRET_API_KEY }}
+  #        NINJA_PROFANITY_FILTER_API_KEY: ${{ secrets.NINJA_PROFANITY_FILTER_API_KEY }}
+  #        KAFKA_BROKER_IP: localhost:9092
 
-      - name: Cleanup Gradle Cache GOOGLE_API_SAFETY_KEY
-        run: |
-          rm -f ~/.gradle/caches/modules-2/modules-2.lock
-          rm -f ~/.gradle/caches/modules-2/gc.properties
+  #    - name: Cleanup Gradle Cache GOOGLE_API_SAFETY_KEY
+  #      run: |
+  #        rm -f ~/.gradle/caches/modules-2/modules-2.lock
+  #        rm -f ~/.gradle/caches/modules-2/gc.properties
 
-      - name: Upload repository as artifact
-        uses: actions/upload-artifact@v3
-        with:
-            name: repo-artifact
-            path: .
-            retention-days: 1
+  #    - name: Upload repository as artifact
+  #      uses: actions/upload-artifact@v3
+  #      with:
+  #          name: repo-artifact
+  #          path: .
+  #          retention-days: 1
   
   deploy:
     runs-on: ubuntu-latest
-    needs: build-test
+    #needs: build-test
     steps:
 
-      - name: Download repository artifact
-        uses: actions/download-artifact@v3
-        with:
-          name: repo-artifact
-          path: .
+    #  - name: Download repository artifact
+    #    uses: actions/download-artifact@v3
+    #    with:
+    #      name: repo-artifact
+    #      path: .
 
       - name: Copy jar file
         run: |
@@ -118,6 +118,7 @@ jobs:
           context: .
           tags: app:latest
           push: false
+          load: true
           build-args: |
             GOOGLE_CLIENT_ID_API_KEY=${{ secrets.GOOGLE_CLIENT_ID_API_KEY }}
             GOOGLE_SAFE_BROWSING_API_KEY=${{ secrets.GOOGLE_API_SAFETY_KEY }}
